"""Add support_level to tickets

Revision ID: 08a4aa025314
Revises: 3d74d63de67e
Create Date: 2026-06-23 23:46:14.980812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a4aa025314'
down_revision: Union[str, Sequence[str], None] = '3d74d63de67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ticketlevel = sa.Enum('L1', 'L2', 'L3', name='ticketlevel')
    ticketlevel.create(op.get_bind(), checkfirst=True)
    op.add_column('tickets', sa.Column('support_level', ticketlevel, nullable=False, server_default='L1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'support_level')
    ticketlevel = sa.Enum('L1', 'L2', 'L3', name='ticketlevel')
    ticketlevel.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
