"""Add ticket priority and assignee

Revision ID: 3d74d63de67e
Revises: e6199ffc5431
Create Date: 2026-06-22 22:58:42.754090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d74d63de67e'
down_revision: Union[str, Sequence[str], None] = 'e6199ffc5431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ticketpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority')
    ticketpriority.create(op.get_bind(), checkfirst=True)
    op.add_column('tickets', sa.Column('priority', ticketpriority, nullable=False, server_default='MEDIUM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'priority')
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
