"""Add sla_due_at to tickets

Revision ID: 8b27fc2ca7ff
Revises: 08a4aa025314
Create Date: 2026-06-24 00:30:33.078970

"""
from typing import Sequence, Union

from alembic import op # pyrefly: ignore [missing-import]
import sqlalchemy as sa # pyrefly: ignore [missing-import]


# revision identifiers, used by Alembic.
revision: str = '8b27fc2ca7ff'
down_revision: Union[str, Sequence[str], None] = '08a4aa025314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("""
        UPDATE tickets
        SET sla_due_at = CASE 
            WHEN priority = 'LOW' THEN created_at + interval '72 hours'
            WHEN priority = 'MEDIUM' THEN created_at + interval '48 hours'
            WHEN priority = 'HIGH' THEN created_at + interval '24 hours'
            WHEN priority = 'CRITICAL' THEN created_at + interval '4 hours'
            ELSE created_at + interval '48 hours'
        END
    """)
    op.alter_column('tickets', 'sla_due_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_due_at')
    # ### end Alembic commands ###
