"""add is_system_account to user

Revision ID: c661b1216b55
Revises: c2ebcc4595f2
Create Date: 2026-06-28 17:34:20.051882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c661b1216b55'
down_revision: Union[str, Sequence[str], None] = 'c2ebcc4595f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_account', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_system_account')
    # ### end Alembic commands ###
