import enum

class NotificationType(str, enum.Enum):
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_REASSIGNED = "TICKET_REASSIGNED"
    TICKET_ESCALATED = "TICKET_ESCALATED"
    TICKET_STATUS_CHANGED = "TICKET_STATUS_CHANGED"
    TICKET_PRIORITY_CHANGED = "TICKET_PRIORITY_CHANGED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_REMOVED = "ROLE_REMOVED"
    FIRST_ROLE_ASSIGNED = "FIRST_ROLE_ASSIGNED"
    SYSTEM = "SYSTEM"
    WELCOME = "WELCOME"
    TICKET_CREATED = "TICKET_CREATED"
